# Generated by Django 2.2 on 2019-04-02 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category_name', models.CharField(max_length=32, verbose_name='新闻分类名称')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conent', models.CharField(max_length=128, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
                'db_table': 'tb_comments',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=64, verbose_name='新闻标题')),
                ('content', models.TextField(default='', verbose_name='新闻内容')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('source', models.CharField(default='官方发布', max_length=32, verbose_name='新闻来源')),
                ('digest', models.CharField(default='', max_length=1024, verbose_name='新闻摘要')),
            ],
            options={
                'verbose_name': '新闻详情',
                'verbose_name_plural': '新闻详情',
                'db_table': 'tb_news',
            },
        ),
        migrations.CreateModel(
            name='ShareNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sharnews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsModel', verbose_name='我的分享')),
            ],
            options={
                'verbose_name': '分享新闻表',
                'verbose_name_plural': '分享新闻表',
                'db_table': 'tb_share_news',
            },
        ),
    ]
