# Generated by Django 2.2 on 2019-04-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '吐槽评论',
                'verbose_name_plural': '吐槽评论',
                'db_table': 'tb_complaint_comments',
            },
        ),
        migrations.CreateModel(
            name='ComplaintCollectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '吐槽收藏',
                'verbose_name_plural': '吐槽收藏',
                'db_table': 'tb_complaint_collections',
            },
        ),
        migrations.CreateModel(
            name='ComplaintCommentLikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '吐槽评论点赞',
                'verbose_name_plural': '吐槽评论点赞',
                'db_table': 'tb_complaint_comment_likes',
            },
        ),
        migrations.CreateModel(
            name='ComplaintLikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '吐槽点赞',
                'verbose_name_plural': '吐槽点赞',
                'db_table': 'tb_complaint_likes',
            },
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('collection_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '吐槽',
                'verbose_name_plural': '吐槽',
                'db_table': 'tb_complaints',
            },
        ),
    ]
